# ライブコーディング用のCloudFormationテンプレート
# create stack: aws cloudformation create-stack --stack-name EipForLiveCoding --template-body file://`pwd`/service/EIP/only_eip.yml
# update stack: aws cloudformation update-stack --stack-name EipForLiveCoding --template-body file://`pwd`/service/EIP/only_eip.yml
# delete stack: aws cloudformation delete-stack --stack-name EipForLiveCoding

AWSTemplateFormatVersion: '2010-09-09'
Description:
  'Ensure Output EIP'

Resources:
  EIPForLive:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: EIPForLive

# EIPのoutput用定義
Outputs:
  OutputEIP:
    Description: Ensure EIP
    Value: !Ref EIPForLive
    Export:
      Name: OutputEIP
