AWSTemplateFormatVersion: '2010-09-09'
Description:
  'Ensure Output EIP'

Resources:
  EIPForLive:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: EIPForLive

# EIPのoutput用定義
Outputs:
  OutputEIP:
    Description: Ensure EIP
    Value: !Ref EIPForLive
    Export:
      Name: OutputEIP
